# Generated by Django 2.2 on 2021-06-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expand_global',
            fields=[
                ('transformation', models.CharField(blank=True, max_length=256, null=True)),
                ('left_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('right_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('transformation_reaction_SMARTS', models.CharField(blank=True, max_length=256, null=True)),
                ('average_change', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('nochange_portion', models.FloatField(blank=True, null=True)),
                ('increase_portion', models.FloatField(blank=True, null=True)),
                ('decrease_portion', models.FloatField(blank=True, null=True)),
                ('transformation_global_ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('statistical_significance', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global Information',
                'verbose_name_plural': 'Global Information',
                'ordering': ['statistical_significance', 'variance'],
            },
        ),
        migrations.CreateModel(
            name='Expand_local',
            fields=[
                ('transformation', models.CharField(blank=True, max_length=256, null=True)),
                ('left_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('right_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('transformation_reaction_SMARTS', models.CharField(blank=True, max_length=256, null=True)),
                ('env_1', models.CharField(blank=True, max_length=32, null=True)),
                ('env_2', models.CharField(blank=True, max_length=32, null=True)),
                ('env_3', models.CharField(blank=True, max_length=32, null=True)),
                ('average_change', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('nochange_portion', models.FloatField(blank=True, null=True)),
                ('increase_portion', models.FloatField(blank=True, null=True)),
                ('decrease_portion', models.FloatField(blank=True, null=True)),
                ('transformation_local_ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('statistical_significance', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('structure_local_ID', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Local Information',
                'verbose_name_plural': 'Local Information',
            },
        ),
        migrations.CreateModel(
            name='Expand_Sortlist',
            fields=[
                ('sortlist1', models.CharField(blank=True, max_length=512, null=True)),
                ('sortlist2', models.CharField(blank=True, max_length=512, null=True)),
                ('sortlist', models.CharField(blank=True, max_length=512, null=True)),
                ('structure_global_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('transformation', models.CharField(blank=True, max_length=256, null=True)),
                ('left_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('right_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('transformation_reaction_SMARTS', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Structure Information',
                'verbose_name_plural': 'Structure Information',
            },
        ),
        migrations.CreateModel(
            name='Experi_global',
            fields=[
                ('transformation', models.CharField(blank=True, max_length=256, null=True)),
                ('left_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('right_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('transformation_reaction_SMARTS', models.CharField(blank=True, max_length=256, null=True)),
                ('average_change', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('nochange_portion', models.FloatField(blank=True, null=True)),
                ('increase_portion', models.FloatField(blank=True, null=True)),
                ('decrease_portion', models.FloatField(blank=True, null=True)),
                ('transformation_global_ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('statistical_significance', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global Information',
                'verbose_name_plural': 'Global Information',
                'ordering': ['statistical_significance', 'variance'],
            },
        ),
        migrations.CreateModel(
            name='Experi_local',
            fields=[
                ('transformation', models.CharField(blank=True, max_length=256, null=True)),
                ('left_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('right_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('transformation_reaction_SMARTS', models.CharField(blank=True, max_length=256, null=True)),
                ('env_1', models.CharField(blank=True, max_length=32, null=True)),
                ('env_2', models.CharField(blank=True, max_length=32, null=True)),
                ('env_3', models.CharField(blank=True, max_length=32, null=True)),
                ('average_change', models.FloatField(blank=True, null=True)),
                ('count', models.FloatField(blank=True, null=True)),
                ('nochange_portion', models.FloatField(blank=True, null=True)),
                ('increase_portion', models.FloatField(blank=True, null=True)),
                ('decrease_portion', models.FloatField(blank=True, null=True)),
                ('transformation_local_ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('statistical_significance', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('structure_local_ID', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Local Information',
                'verbose_name_plural': 'Local Information',
            },
        ),
        migrations.CreateModel(
            name='Experi_Sortlist',
            fields=[
                ('sortlist1', models.CharField(blank=True, max_length=512, null=True)),
                ('sortlist2', models.CharField(blank=True, max_length=512, null=True)),
                ('sortlist', models.CharField(blank=True, max_length=512, null=True)),
                ('structure_global_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('transformation', models.CharField(blank=True, max_length=256, null=True)),
                ('left_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('right_fragment', models.CharField(blank=True, max_length=128, null=True)),
                ('transformation_reaction_SMARTS', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Structure Information',
                'verbose_name_plural': 'Structure Information',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property', models.CharField(blank=True, max_length=32, null=True)),
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Property Information',
                'verbose_name_plural': 'Property Information',
            },
        ),
        migrations.CreateModel(
            name='Experi_Property_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Property')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Experi_Sortlist')),
            ],
            options={
                'verbose_name': 'Property Information',
                'verbose_name_plural': 'Property Information',
            },
        ),
        migrations.CreateModel(
            name='Experi_MMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.FloatField(blank=True, null=True)),
                ('value_l', models.FloatField(blank=True, null=True)),
                ('value_r', models.FloatField(blank=True, null=True)),
                ('molecule_l', models.CharField(blank=True, max_length=512, null=True)),
                ('molecule_r', models.CharField(blank=True, max_length=512, null=True)),
                ('transformation_global_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Experi_global')),
                ('transformation_local_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Experi_local')),
            ],
            options={
                'verbose_name': 'MMP Information',
                'verbose_name_plural': 'MMP Information',
            },
        ),
        migrations.AddField(
            model_name='experi_local',
            name='structure_global_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Experi_Sortlist'),
        ),
        migrations.AddField(
            model_name='experi_local',
            name='transformation_global_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Experi_global'),
        ),
        migrations.AddField(
            model_name='experi_global',
            name='structure_global_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Experi_Sortlist'),
        ),
        migrations.CreateModel(
            name='Expand_Property_Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Property')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Expand_Sortlist')),
            ],
            options={
                'verbose_name': 'Property Information',
                'verbose_name_plural': 'Property Information',
            },
        ),
        migrations.CreateModel(
            name='Expand_MMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.FloatField(blank=True, null=True)),
                ('value_l', models.FloatField(blank=True, null=True)),
                ('value_r', models.FloatField(blank=True, null=True)),
                ('molecule_l', models.CharField(blank=True, max_length=512, null=True)),
                ('molecule_r', models.CharField(blank=True, max_length=512, null=True)),
                ('transformation_global_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Expand_global')),
                ('transformation_local_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Expand_local')),
            ],
            options={
                'verbose_name': 'MMP Information',
                'verbose_name_plural': 'MMP Information',
            },
        ),
        migrations.AddField(
            model_name='expand_local',
            name='structure_global_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Expand_Sortlist'),
        ),
        migrations.AddField(
            model_name='expand_local',
            name='transformation_global_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Expand_global'),
        ),
        migrations.AddField(
            model_name='expand_global',
            name='structure_global_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Expand_Sortlist'),
        ),
    ]
