# Generated by Django 2.2 on 2021-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210624_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='expand_sortlist',
            name='left_fragment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='expand_sortlist',
            name='right_fragment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='expand_sortlist',
            name='transformation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='expand_sortlist',
            name='transformation_reaction_SMARTS',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
