# Generated by Django 2.2 on 2023-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admetproperty',
            name='md5',
            field=models.CharField(default='', max_length=128),
        ),
    ]
